### ISSUE TITLE
SNMPv3

### ISSUE THREAD

**Issue by sbakara** [djamp42/csv2librenms#2]
Hi there! Possible to share a script edit compatible with SNMPv3 please? I tried editing from"v2c" to "v3c" and "v3" but it didn't work.

**Comment by djamp42** [comment]
Check out this fork, https://github.com/AndrewPiroli/csv2librenms

I might add SNMPv3 eventually, but would most likely just use this if i needed too..

**Comment by sbakara** [comment]
Appreciated

>
